import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navber";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Generated Ai Image",
  description: "IMG Generated by ChatGTP",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.className} h-full antialiased`}
    >
      <body className="">
        <Navbar/>
        <main className="max-w-7xl sm:container w-[85%] mx-auto px-5">{children}</main>
        <Footer/>
        <ToastContainer />
        </body>
    </html>
  );
}
