import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navber";
import Footer from "@/components/Footer";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Generated Ai Image",
  description: "IMG Generated by ChatGTP",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.className} h-full antialiased`}
    >
      <body className="">\
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
